# Generated by Django 3.2.3 on 2021-06-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=0, upload_to='uploads/category/'),
            preserve_default=False,
        ),
    ]
