# Generated by Django 3.2.3 on 2021-07-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_vlogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='About_us')),
            ],
        ),
    ]
